load("//:zinnia_lang.bzl", "zinnia_binary")

package(
    default_visibility = ["//visibility:public"],
)

zinnia_binary(
    name = "annotations_test",
    main = "annotations_test.zn",
)

zinnia_binary(
    name = "data_test",
    main = "data_test.zn",
)

zinnia_binary(
    name = "inject_test",
    main = "inject_test.zn",
)

zinnia_binary(
    name = "json_test",
    main = "json_test.zn",
)

zinnia_binary(
    name = "time_test",
    main = "time_test.zn",
)
