load("//:jasper_lang.bzl", "jasper_binary")

package(
    default_visibility = ["//visibility:public"],
)

jasper_binary(
    name = "annotations_test",
    main = "annotations_test.jp",
)

jasper_binary(
    name = "data_test",
    main = "data_test.jp",
)

jasper_binary(
    name = "inject_test",
    main = "inject_test.jp",
)

jasper_binary(
    name = "json_test",
    main = "json_test.jp",
)

jasper_binary(
    name = "time_test",
    main = "time_test.jp",
)
