load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    "intern",
    srcs = ["intern.c"],
    hdrs = ["intern.h"],
    deps = [
        "@memory-wrapper//alloc/arena:intern",
    ],
)
