load("//:zinnia_lang.bzl", "zinnia_binary")

package(
    default_visibility = ["//visibility:public"],
)

zinnia_binary(
    name = "builder",
    main = "builder.zn",
)

zinnia_binary(
    name = "mvc",
    main = "mvc.zn",
)
