load("//:jasper_lang.bzl", "jasper_binary")

package(
    default_visibility = ["//visibility:public"],
)

jasper_binary(
    name = "builder",
    main = "builder.jp",
)

jasper_binary(
    name = "mvc",
    main = "mvc.jp",
)
