load("//zinnia:zinnia.bzl", "zinnia_binary")

package(
    default_visibility = ["//zinnia:internal"],
)

zinnia_binary(
    name = "module",
    srcs = glob(["**/*.*"]),
    main = "module.zn",
)
