load("//:zinnia_lang.bzl", "zinnia_binary")

package(
    default_visibility = ["//visibility:public"],
)

zinnia_binary(
    name = "completers",
    main = "completers.zn",
)

zinnia_binary(
    name = "futures",
    main = "futures.zn",
)

zinnia_binary(
    name = "process",
    main = "process.zn",
)

zinnia_binary(
    name = "remotes",
    main = "remotes.zn",
)
