load("//:jasper_lang.bzl", "jasper_binary")

package(
    default_visibility = ["//visibility:public"],
)

jasper_binary(
    name = "completers",
    main = "completers.jp",
)

jasper_binary(
    name = "futures",
    main = "futures.jp",
)

jasper_binary(
    name = "process",
    main = "process.jp",
)

jasper_binary(
    name = "remotes",
    main = "remotes.jp",
)
