load("//:jeff_lang.bzl", "jeff_vm_binary")

package(
    default_visibility = ["//visibility:public"],
)

jeff_vm_binary(
    name = "completers",
    main = "completers.jp",
)

jeff_vm_binary(
    name = "futures",
    main = "futures.jp",
)
