load("//zinnia:zinnia.bzl", "zinnia_test")

package(
    default_visibility = ["//visibility:private"],
)

zinnia_test(
    name = "annotations_test",
    main = "annotations_test.zn",
)

zinnia_test(
    name = "data_test",
    main = "data_test.zn",
)

zinnia_test(
    name = "inject_test",
    main = "inject_test.zn",
)

zinnia_test(
    name = "json_test",
    main = "json_test.zn",
)

zinnia_test(
    name = "module_test",
    main = "module_test.zn",
    deps = ["//examples/module:module_srcs"],
)

zinnia_test(
    name = "time_test",
    main = "time_test.zn",
)

zinnia_test(
    name = "strfmt_test",
    main = "strfmt_test.zn",
)
