#ifndef COM_GITHUB_JEFFMANZIONE_ZINNIA_EXAMPLES_STATIC_PID_H_
#define COM_GITHUB_JEFFMANZIONE_ZINNIA_EXAMPLES_STATIC_PID_H_

#include "zinnia/native.h"

NATIVE_FN void init_pid(ModuleBuilder *builder);

#endif /* COM_GITHUB_JEFFMANZIONE_ZINNIA_EXAMPLES_STATIC_PID_H_ */