load("@jeffmanzione_language_tools//language-tools/lexer:lexer_builder.bzl", "lexer_builder")

package(
    default_visibility = ["//zinnia:internal"],
)

lexer_builder(
    name = "lang_lexer",
    comments = "comments.txt",
    keywords = "keywords.txt",
    strings = "strings.txt",
    symbols = "symbols.txt",
)
