#ifndef COM_GITHUB_JEFFMANZIONE_ZINNIA_EXAMPLES_SEED_HELLO_H_
#define COM_GITHUB_JEFFMANZIONE_ZINNIA_EXAMPLES_SEED_HELLO_H_

#include "zinnia/native.h"

NATIVE_FN void init_hello(ModuleBuilder *builder);

#endif /* COM_GITHUB_JEFFMANZIONE_ZINNIA_EXAMPLES_SEED_HELLO_H_ */