load("//:jeff_lang.bzl", "jeff_vm_binary")

package(
    default_visibility = ["//visibility:public"],
)

jeff_vm_binary(
    name = "arguments",
    main = "arguments.jp",
    deps = [],
)

jeff_vm_binary(
    name = "exceptions",
    main = "exceptions.jp",
    deps = [],
)

jeff_vm_binary(
    name = "fibonacci",
    main = "fibonacci.jp",
    deps = [],
)

jeff_vm_binary(
    name = "hello",
    main = "hello.jp",
)

jeff_vm_binary(
    name = "range",
    main = "range.jp",
)
