load("//:jasper_lang.bzl", "jasper_binary")

package(
    default_visibility = ["//visibility:public"],
)

jasper_binary(
    name = "arguments",
    main = "arguments.jp",
    deps = [],
)

jasper_binary(
    name = "exceptions",
    main = "exceptions.jp",
    deps = [],
)

jasper_binary(
    name = "fibonacci",
    main = "fibonacci.jp",
)

jasper_binary(
    name = "hello",
    main = "hello.jp",
)

jasper_binary(
    name = "range",
    main = "range.jp",
)
