load("//:jeff_lang.bzl", "jeff_vm_binary")

package(
    default_visibility = ["//visibility:public"],
)

jeff_vm_binary(
    name = "arguments",
    main = "arguments.jv",
    deps = [],
)

jeff_vm_binary(
    name = "fibonacci",
    main = "fibonacci.jv",
    deps = [],
)

jeff_vm_binary(
    name = "hello",
    main = "hello.jv",
)
