load("//:zinnia_lang.bzl", "zinnia_binary")

package(
    default_visibility = ["//visibility:public"],
)

zinnia_binary(
    name = "date",
    main = "date.zn",
)

zinnia_binary(
    name = "time",
    main = "time.zn",
)

zinnia_binary(
    name = "timestamp",
    main = "timestamp.zn",
)
