load("//zinnia:zinnia.bzl", "zinnia_binary")

zinnia_binary(
    name = "date",
    main = "date.zn",
)

zinnia_binary(
    name = "timer",
    main = "timer.zn",
)

zinnia_binary(
    name = "timestamp",
    main = "timestamp.zn",
)
