load("//zinnia:zinnia.bzl", "zinnia_binary")

zinnia_binary(
    name = "chat",
    main = "chat.zn",
)

zinnia_binary(
    name = "http_hello",
    main = "http_hello.zn",
)

zinnia_binary(
    name = "message",
    main = "message.zn",
)

zinnia_binary(
    name = "simple_http",
    main = "simple_http.zn",
)

zinnia_binary(
    name = "webserver",
    main = "webserver.zn",
)

zinnia_binary(
    name = "local",
    main = "local.zn",
)
