load("//:jeff_lang.bzl", "jeff_vm_binary")

package(
    default_visibility = ["//visibility:public"],
)

jeff_vm_binary(
    name = "chat",
    main = "chat.jv",
    deps = [],
)

jeff_vm_binary(
    name = "http_hello",
    main = "http_hello.jv",
    deps = [],
)

jeff_vm_binary(
    name = "webserver",
    main = "webserver.jv",
    deps = [],
)
