load("//:jasper_lang.bzl", "jasper_binary")

package(
    default_visibility = ["//visibility:public"],
)

jasper_binary(
    name = "chat",
    main = "chat.jp",
    deps = [],
)

jasper_binary(
    name = "http_hello",
    main = "http_hello.jp",
    deps = [],
)

jasper_binary(
    name = "webserver",
    main = "webserver.jp",
    deps = [],
)
